<?php

namespace Vokuro\Models;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Validator\InclusionIn;
use Phalcon\Mvc\Model\Validator\Numericality;

/**
 * BusinessSubscriptionPlan
 * 
 * @package Vokuro\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-05-23, 18:25:37
 */
class BusinessSubscriptionPlan extends Model
{
    public $id;
    public $locations;
    public $sms_messages_per_location;
    public $payment_plan;
    public $subscription_pricing_plan_id;
    public $user_id;
    public $created_at;
    public $update_at;
    public $deleted_at;
    
    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->skipAttributesOnCreate(['updated_at']);
        $this->belongsTo('user_id', 'Vokuro\Models\Users', 'id', ['alias' => 'Users']);
    }
    
    /**
     * Validation method for model.
     */
    public function validation()
    {
        return true;//$pass && $this->validationHasFailed() != true;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'business_subscription_plan';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BusinessSubscriptionPlan[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BusinessSubscriptionPlan
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'locations' => 'locations',
            'sms_messages_per_location' => 'sms_messages_per_location',
            'payment_plan' => 'payment_plan',
            'subscription_pricing_plan_id' => 'subscription_pricing_plan_id',
            'user_id' => 'user_id',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'deleted_at' => 'deleted_at' 
        );
    }

}
