<?php

namespace Vokuro\Models;

use Phalcon\Mvc\Model;

/**
 * SubscriptionPricingPlanHasParameterList
 * 
 * @package Vokuro\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-05-23, 13:17:47
 */
class SubscriptionPricingPlanHasParameterList extends Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $subscription_pricing_plan_id;

    /**
     *
     * @var string
     */
    protected $parameter_list_id;
    
    /**
     *
     * @var integer
     */
    protected $created_at;
    
    /**
     *
     * @var integer
     */
    protected $update_at;
    
    /**
     *
     * @var integer
     */
    protected $deleted_at;
    
    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field subscription_pricing_plan_id
     *
     * @param string $subscription_pricing_plan_id
     * @return $this
     */
    public function setSubscriptionPricingPlanId($subscription_pricing_plan_id)
    {
        $this->subscription_pricing_plan_id = $subscription_pricing_plan_id;

        return $this;
    }

    /**
     * Method to set the value of field parameter_list_id
     *
     * @param string $parameter_list_id
     * @return $this
     */
    public function setParameterListId($parameter_list_id)
    {
        $this->parameter_list_id = $parameter_list_id;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field subscription_pricing_plan_id
     *
     * @return string
     */
    public function getSubscriptionPricingPlanId()
    {
        return $this->subscription_pricing_plan_id;
    }

    /**
     * Returns the value of field parameter_list_id
     *
     * @return string
     */
    public function getParameterListId()
    {
        return $this->parameter_list_id;
    }
    
    public function initialize()
    {
        $this->belongsTo('subscription_pricing_plan_id', "Vokuro\Models\SubscriptionPricingPlan", "id", ['alias' => 'SubscriptionPricingPlan']);
        $this->belongsTo('parameter_list_id', "Vokuro\Models\SubscriptionPricingPlanParameterList", "id", ['alias' => 'SubscriptionPricingPlanParameterList']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'subscription_pricing_plan_has_parameter_list';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionPricingPlanHasParameterList[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionPricingPlanHasParameterList
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'subscription_pricing_plan_id' => 'subscription_pricing_plan_id',
            'parameter_list_id' => 'parameter_list_id'
        );
    }

}
