<?php

namespace Vokuro\Models;

/**
 * SubscriptionProfileHasParameterList
 * 
 * @package Vokuro\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-05-23, 13:17:47
 */
class SubscriptionProfileHasParameterList extends Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $subscription_profile_id;

    /**
     *
     * @var string
     */
    protected $parameter_list_id;

    
    public function initialize()
    {
        $this->belongsTo('subscription_profile_id', "SubscriptionProfile", "id");
        $this->belongsTo('parameter_list_id', "SubscriptionProfileParameterList", "id");
    }
    
    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field subscription_profile_id
     *
     * @param string $subscription_profile_id
     * @return $this
     */
    public function setSubscriptionProfileId($subscription_profile_id)
    {
        $this->subscription_profile_id = $subscription_profile_id;

        return $this;
    }

    /**
     * Method to set the value of field parameter_list_id
     *
     * @param string $parameter_list_id
     * @return $this
     */
    public function setParameterListId($parameter_list_id)
    {
        $this->parameter_list_id = $parameter_list_id;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field subscription_profile_id
     *
     * @return string
     */
    public function getSubscriptionProfileId()
    {
        return $this->subscription_profile_id;
    }

    /**
     * Returns the value of field parameter_list_id
     *
     * @return string
     */
    public function getParameterListId()
    {
        return $this->parameter_list_id;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'subscription_profile_has_parameter_list';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionProfileHasParameterList[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionProfileHasParameterList
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'subscription_profile_id' => 'subscription_profile_id',
            'parameter_list_id' => 'parameter_list_id'
        );
    }

}
