<?php

    namespace Vokuro\Models;

    use Phalcon\Mvc\Model;
    use Phalcon\Mvc\Model\Behavior\SoftDelete;

    /**
     * SubscriptionPricingPlanParameterList
     *
     * @package Vokuro\Models
     * @autogenerated by Phalcon Developer Tools
     * @date 2016-05-23, 13:16:41
     */
    class SubscriptionPricingPlanParameterList extends Model
    {
        public $id;
        public $subscription_pricing_plan_id;
        public $min_locations;
        public $max_locations;
        public $location_discount_percentage;
        public $base_price;
        public $sms_charge;
        public $total_price;
        public $location_discount;
        public $upgrade_discount;
        public $discount_price;
        public $sms_messages;
        public $sms_cost;
        public $profit_per_location;
        public $created_at;
        public $updated_at;
        public $deleted_at;

        public function initialize()
        {
            $this->addBehavior(
                new SoftDelete(
                    array(
                        'field' => 'deleted_at',
                        'value' => time()
                    )
                )
            );

            $this->skipAttributesOnCreate(array('updated_at'));

            // $this->belongsTo("subscription_pricing_plan_id", "\Vokuro\Models\SubscriptionPricingPlan", "id", ['alias' => 'SubscriptionPricingPlan']);
        }

        public function validation()
        {
            return true;
        }

        /**
         * Returns table name mapped in the model.
         *
         * @return string
         */
        public function getSource()
        {
            return 'subscription_pricing_plan_parameter_list';
        }

        /**
         * Independent Column Mapping.
         * Keys are the real names in the table and the values their names in the application
         *
         * @return array
         */
        public function columnMap()
        {
            return array(
                'id' => 'id',
                'subscription_pricing_plan_id' => 'subscription_pricing_plan_id',
                'min_locations' => 'min_locations',
                'max_locations' => 'max_locations',
                'location_discount_percentage' => 'location_discount_percentage',
                'base_price' => 'base_price',
                'sms_charge' => 'sms_charge',
                'total_price' => 'total_price',
                'location_discount' => 'location_discount',
                'upgrade_discount' => 'upgrade_discount',
                'discount_price' => 'discount_price',
                'sms_messages' => 'sms_messages',
                'sms_cost' => 'sms_cost',
                'profit_per_location' => 'profit_per_location',
                'created_at' => 'created_at',
                'updated_at' => 'updated_at',
                'deleted_at' => 'deleted_at'
            );
        }

    }
