<?php

namespace Vokuro\Models;

/**
 * SubscriptionProfileParameterList
 * 
 * @package Vokuro\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-05-23, 13:16:41
 */
class SubscriptionProfileParameterList extends Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $min_locations;

    /**
     *
     * @var integer
     */
    protected $max_locations;

    /**
     *
     * @var double
     */
    protected $discount;
    
    /**
     *
     * @var integer
     */
    protected $created_at;
    
    /**
     *
     * @var integer
     */
    protected $update_at;
    
    /**
     *
     * @var integer
     */
    protected $deleted_at;

    
    public function initialize()
    {
        $this->hasMany("id", "SubscriptionProfileHasParameterList", "parameter_list_id");
    }
    
    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field min_locations
     *
     * @param integer $min_locations
     * @return $this
     */
    public function setMinLocations($min_locations)
    {
        $this->min_locations = $min_locations;

        return $this;
    }

    /**
     * Method to set the value of field max_locations
     *
     * @param integer $max_locations
     * @return $this
     */
    public function setMaxLocations($max_locations)
    {
        $this->max_locations = $max_locations;

        return $this;
    }

    /**
     * Method to set the value of field discount
     *
     * @param double $discount
     * @return $this
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }
    
    /**
     * Method to set the value of field created_at
     *
     * @param integer $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }
    
    /**
     * Method to set the value of field updated_at
     *
     * @param integer $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    
    /**
     * Method to set the value of field deleted_at
     *
     * @param integer $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field min_locations
     *
     * @return integer
     */
    public function getMinLocations()
    {
        return $this->min_locations;
    }

    /**
     * Returns the value of field max_locations
     *
     * @return integer
     */
    public function getMaxLocations()
    {
        return $this->max_locations;
    }

    /**
     * Returns the value of field discount
     *
     * @return double
     */
    public function getDiscount()
    {
        return $this->discount;
    }
    
    /**
     * Returns the value of field created_at
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }
    
    /**
     * Returns the value of field updated_at
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }
    
    /**
     * Returns the value of field deleted_at
     *
     * @return integer
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'subscription_profile_parameter_list';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionProfileParameterList[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return SubscriptionProfileParameterList
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'min_locations' => 'min_locations',
            'max_locations' => 'max_locations',
            'discount' => 'discount',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'deleted_at' => 'deleted_at'
        );
    }

}
